name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies on Ubuntu-latest
      run: |
          sudo apt-get update
          sudo apt-get install libmpfr-dev
          gcc --version
          g++ --version
    - name: make
      run: make
